'use client'

import './globals.css'
import { Quicksand } from 'next/font/google'
import { Providers } from './providers'
import { usePathname } from 'next/navigation'
import Nav from '@/components/nav'

const quicksand = Quicksand({subsets: ['vietnamese']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname()

  return (
    <html lang="en">
      <body className={quicksand.className}>
        <Providers>
          { pathname !== '/' && <Nav /> }
          <div className="mx-3 sm:w-screen sm:max-w-5xl sm:mx-auto">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
