import './globals.css'
import { Quicksand } from 'next/font/google'
import { Providers } from './providers'

const quicksand = Quicksand({subsets: ['vietnamese']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
